version: "3.9"
services:

  redis:
    container_name: redis
    image: redis:6.2.4-alpine3.13
    restart: "no"
    command: redis-server --requirepass password
    ports:
      - 6379:6379
    volumes:
      - redis-volume

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:redis-commander-210
    restart: "no"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379:0:password,local:redis:6379:1:password,local:redis:6379:2:password,local:redis:6379:3:password,local:redis:6379:4:password,local:redis:6379:5:password,local:redis:6379:6:password,local:redis:6379:7:password
      - HTTP_USER=user
      - HTTP_PASSWORD=password
    ports:
      - 16379:8081
    volumes:
      - redis-commander-volume

  postgres:
    container_name: postgres
    image: postgres:11.12
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres-volume
 
  postgres-pgadmin4:
    container_name: postgres-pgadmin4
    image:  dpage/pgadmin4:5.4
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - 15432:80
    volumes:
      - postgres-pgadmin4-volume

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-06-09T18-51-39Z
    restart: "no"
    command: server /data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      #- MINIO_BROWSER=off
    ports:
      - 9000:9000
    volumes:
      - minio-volume
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.17-management-alpine
    restart: "no"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672     # AMQP
      - 15671:15671   #
      - 15672:15672   # http (management)
      - 15691:15691   #
      - 15692:15962   # http (prometheus)
      - 25672:25672   # clustering
    volumes:
      - rabbitmq-volume

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.28.0
    restart: "no"
    ports:
      - 9090:9090
    volumes:
      - prometheus-volume

volumes:
  redis-volume:
    driver: local
  redis-commander-volume:
    driver: local
  postgres-volume:
    driver: local
  postgres-pgadmin4-volume:
    driver: local
  minio-volume:
    driver: local
  rabbitmq-volume:
    driver: local
  prometheus-volume:
    driver: local